name: parrot_shelf
description: Shelf support module for Parrot framework
version: 0.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  shelf: ^1.3.2
  parrot: ^0.0.1
  shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  parrot:
    path: ../parrot
