name: parrot_commander
description: Parrot commander, Modular command line interface for Parrot.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.3.1
  parrot: ^0.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  parrot_mirror:
    path: ../parrot_mirror

dependency_overrides:
  parrot:
    path: ../parrot
