name: parrot
description: > 
  Parrot is a modular Dart framework for building efficient, reliable, and scalable applications.
version: 0.0.3
repository: https://github.com/odroe/parrot

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
