name: parrot
description: > 
  Parrot is a modular Dart framework for building efficient, reliable, and scalable applications.
version: 0.0.6
repository: https://github.com/odroe/parrot

environment:
  sdk: '<4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.6
