name: parrot
description: >
  Parrot is a progressive Dart framework for building efficient, reliable and scalable server-side applications.
version: 0.0.2
repository: https://github.com/odroe/parrot

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.1
  coverage: ^1.6.0
  lints: ^2.0.0
  mockito: ^5.3.1
  test: ^1.21.6
