name: parrot_mirror
description: Parrot modular compiler that uses `dart:mirrors` for content parsing and context into containers.
version: 1.0.0
repository: https://github.com/odroe/parrot
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  parrot: ^0.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  parrot:
    path: ../parrot
