name: parrot_cmd
description: A starting point for Dart libraries or applications.
version: 0.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  args: ^2.3.1
  parrot: ^0.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
