name: parrot_cmd
description: Parrot module for building modular command line applications.
version: 0.0.0
repository: https://github.com/odroe/parrot

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  args: ^2.3.1
  parrot: ^0.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
