name: parrot_cmd
description: Parrot module for building modular command line applications.
version: 0.0.0
repository: https://github.com/odroe/parrot

environment:
  sdk: '<4.0.0'

dependencies: 
  args: ^2.3.1
  parrot: ^0.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
