name: parrot_02_shelf
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  parrot: ^0.0.1
  parrot_shelf: ^0.0.0
dependency_overrides:
  parrot:
    path: ../../packages/parrot
  parrot_shelf:
    path: ../../packages/parrot_shelf