name: Parrot Analyze
on: [push, pull_request]
jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - packages/parrot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ matrix.package }}
      - name: Test with Coverage
        working-directory: ${{ matrix.package }}
        run: dart run coverage:test_with_coverage -o coverage
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ${{ matrix.package }}/coverage/lcov.info
          flags: ${{ matrix.package }}
          name: ${{ matrix.package }}
          