name: analyze
on: [push, pull_request]
jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - parrot
          - parrot_cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.4
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
        working-directory: packages/${{ matrix.package }}
      - name: Analyze ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: dart analyze
          