# Check that each package/*/LICENSE is consistent with LICENSE.
#
# - If it does not exist, make a copy of the LICENSE.
# - If there is an inconsistency, overwrite with LICENSE.
name: License Consistency
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get
        working-directory: tools
      - name: Fix license consistency
        run: dart run tools/license_consistency.dart -l LICENSE -f LICENSE -d packages
      - name: Check for fix license inconsistency
        run: |
          if [[ -n $(git status -s) ]]; then exit 1; fi
  create-pr:
    if: ${{ failure() }}
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get
        working-directory: tools
      - name: Fix license consistency
        run: dart run tools/license_consistency.dart -l LICENSE -f LICENSE -d packages
      - name: Output Changed Files
        id: changed-files
        run: echo "::set-output name=files::$(git status -s)"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "fix(license): Fix license inconsistency"
          title: Fix license inconsistency
          body: |
            This PR was created by a tool. It checks that each packages/*/LICENSE is consistent with LICENSE.
            
            ```
            ${{ steps.changed-files.outputs.files }}
            ```
          branch: license-consistency
          delete-branch: true