name: Parrot Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - parrot
        sdk:
          - stable
          - 2.18.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
        working-directory: packages/${{ matrix.package }}
      - name: Run tests
        run: dart test -r github
        working-directory: packages/${{ matrix.package }}
